DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS sessions;

ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "owner_currency_key";
ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "accounts_owner_fkey";
ALTER TABLE "users" DROP COLUMN "is_email_verified";
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS verify_emails CASCADE;